# Site settings
title: Varlinor’s WIKI
email: weiyupiaoran@gmail.com
description: “start building my wiki station!”
baseurl: ""  
url: "http://yourdomain.com"
twitter_username: varlinor
github_username:  shangyue1110

# Build settings
markdown: kramdown
permalink: pretty
